version = "MatteFormer-Composition1k"
dist = false

[model]
trimap_channel = 3
mask_channel = 1
batch_size = 2
imagenet_pretrain = true
imagenet_pretrain_path = "pretrained/swin_tiny_patch4_window7_224.pth"
self_refine_width1 = 30
self_refine_width2 = 15

[train]
total_step = 100
warmup_step = 10

val_step = 40

clip_grad = true
G_lr = 1e-3
rec_weight = 1.0
comp_weight = 1.0
lap_weight = 1.0


[data]
train_fg = "/media/gt-ubuntu/Storage_SSD1T/Data/Matting/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Adobe-licensed images/fg"
train_alpha = "/media/gt-ubuntu/Storage_SSD1T/Data/Matting/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Adobe-licensed images/alpha"
train_bg = "/media/gt-ubuntu/Storage_SSD1T/Data/COCO/coco2014/train2014"

test_merged = "/media/gt-ubuntu/Storage_SSD1T/Data/Matting/Adobe_Deep_Matting_Dataset/Combined_Dataset/Test_set/Adobe-licensed images/merged"
test_alpha = "/media/gt-ubuntu/Storage_SSD1T/Data/Matting/Adobe_Deep_Matting_Dataset/Combined_Dataset/Test_set/Adobe-licensed images/alpha_copy"
test_trimap = "/media/gt-ubuntu/Storage_SSD1T/Data/Matting/Adobe_Deep_Matting_Dataset/Combined_Dataset/Test_set/Adobe-licensed images/trimaps"

workers = 0
crop_size = 512

cutmask_prob = 0.25
augmentation = true
random_interp = true
real_world_aug = false

[log]
experiment_root = "experiments"

logging_path = "logs/txt"
logging_step =  1
logging_level = "INFO"

checkpoint_path = "checkpoints"
checkpoint_step = 40